%% Import data from text file.
% Script for importing data from the following text file:
%
%    /Users/jutraman/Documents/ML-COMP3009UNUK/Cousework/DecisionTrees/nursery.txt
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2020/11/24 05:24:55

%% Initialize variables.
filename = '/Users/jutraman/Documents/ML-COMP3009UNUK/Cousework/DecisionTrees/nursery.txt';
delimiter = ',';

%% Format for each line of text:
%   column1: categorical (%C)
%	column2: categorical (%C)
%   column3: categorical (%C)
%	column4: categorical (%C)
%   column5: categorical (%C)
%	column6: categorical (%C)
%   column7: categorical (%C)
%	column8: categorical (%C)
%   column9: categorical (%C)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%C%C%C%C%C%C%C%C%C%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'TextType', 'string', 'EmptyValue', NaN,  'ReturnOnError', false);

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Create output variable
nursery = table(dataArray{1:end-1}, 'VariableNames', {'parents','has_nurs','form','children','housing','finance','social','health','class'});

%% Clear temporary variables
clearvars filename delimiter formatSpec fileID dataArray ans;